### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/private-events#1]
Your comments are welcome.

**Comment by rammazzoti2000** [comment]
Het @patriciachrysy, you did great work on the styling, also implementing the invitation which only invited users can attend events.
I noticed you have `user_signed_in` for  `events_controller` and `user_already_signed_in` for user_controller; since the controllers inherit from `ApplicationController` those methods could be placed inside there and just call the methods when needed inside each controller

As for the singin / signup process and creation of a new session would be great to have them in a dedicated session controller

Overall the project looks great and it has a solid logic, congratulations on the achievement

**Comment by nyatindopatrick** [comment]
Looks good. Great work!

**Comment by dili021** [comment]
Nice work on the styling partner!
